# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: nivaldoandrade
# "service" is the name of this project. This will also be added to your AWS resource names.
service: serverless-api

provider:
  name: aws
  runtime: nodejs22.x
  architecture: arm64
  memorySize: 128
  region: sa-east-1
  httpApi:
    cors: true
  environment:
    FILE_BUCKET_NAME: !Ref FileBucket
    TABLE_NAME: !Ref MainTable
  iam:
    role:
      statements:
        - Effect: Allow
          Action: s3:PutObject
          Resource: !Sub ${FileBucket.Arn}/*
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:UpdateItem
          Resource: !Sub ${MainTable.Arn}


package:
  individually: true

build:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    exclude:
      - '@aws-sdk/*'
    external:
      - '@aws-sdk/*'

resources:
  Resources:
    FileBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-${sls:stage}-file-bucket
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - '*'
              AllowedMethods:
                - PUT
              AllowedOrigins:
                - 'http://localhost:5173'
    MainTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${sls:stage}-MainTable
        BillingMode: PAY_PER_REQUEST
        TimeToLiveSpecification:
          AttributeName: expireAt
          Enabled: true
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH


functions:
  createImage:
    handler: src/functions/createImage.handler
    events:
      - httpApi:
          path: /create-image
          method: post
  newUploadFileTrigger:
    handler: src/functions/triggers/newUploadFileTrigger.handler
    events:
      - s3:
          bucket: !Ref FileBucket
          event: s3:ObjectCreated:Put
          existing: true
          forceDeploy: true
