# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: nivaldoandrade
# "service" is the name of this project. This will also be added to your AWS resource names.
service: serverless-api

provider:
  name: aws
  runtime: nodejs22.x
  architecture: arm64
  memorySize: 128
  region: sa-east-1
  environment:
    FILE_BUCKET_NAME: !Ref FileBucket
  iam:
    role:
      statements:
        - Effect: Allow
          Action: s3:PutObject
          Resource: !Sub ${FileBucket.Arn}/*


package:
  individually: true

build:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    exclude:
      - '@aws-sdk/*'
    external:
      - '@aws-sdk/*'

resources:
  Resources:
    FileBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-${sls:stage}-file-bucket


functions:
  createImage:
    handler: src/functions/createImage.handler
    events:
      - httpApi:
          path: /create-image
          method: post
